-- Example INSERT statements for CONSULTORIO table
INSERT INTO CONSULTORIO (NUMERO_CONSULTORIO, PISO) VALUES (101, 1);
INSERT INTO CONSULTORIO (NUMERO_CONSULTORIO, PISO) VALUES (202, 2);
INSERT INTO CONSULTORIO (NUMERO_CONSULTORIO, PISO) VALUES (303, 3);
INSERT INTO CONSULTORIO (NUMERO_CONSULTORIO, PISO) VALUES (404, 4);
INSERT INTO CONSULTORIO (NUMERO_CONSULTORIO, PISO) VALUES (505, 5);

-- Example INSERT statements for DOCTOR table
INSERT INTO DOCTOR (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('John', 'Smith', 'Doe', 'Cardiology');
INSERT INTO DOCTOR (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('Jane', 'Johnson', 'Smith', 'Pediatrics');
INSERT INTO DOCTOR (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('Robert', 'Williams', 'Brown', 'Orthopedics');
INSERT INTO DOCTOR (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('Emily', 'Jones', 'Taylor', 'Dermatology');
INSERT INTO DOCTOR (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('Michael', 'Anderson', 'Davis', 'Neurology');
